version: "3.8"
services:
  planka:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["1337:1337"]
    environment:
      BASE_URL: "https://tasks.joshuascutts.com"
      # Keep this clean: just ssl=true (node-postgres understands this)
      DATABASE_URL: "postgresql://planka:PlankaSecure2024DBPassword@planka-db-new.c32zqm4pnkzf.ap-southeast-2.rds.amazonaws.com:5432/planka?ssl=true"

      TRUST_PROXY: "1"
      # First boot only; remove after login
      DEFAULT_ADMIN_EMAIL: "admin@yourdomain.com"
      DEFAULT_ADMIN_PASSWORD: "ChangeMe123"
      DEFAULT_ADMIN_NAME: "Admin"
      DEFAULT_ADMIN_USERNAME: "admin"
